name: Build
run-name: "Build #${{ github.run_number }}"

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build-jvm:
    name: Build JVM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: 📦 Build JVM
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: jvmJar
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
          gradle-distribution-sha-256-sum-warning: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JVM
        uses: actions/upload-artifact@v4
        with:
          name: jvm-package
          path: build/libs/pakku.jar

  build-jvm-dist:
    name: Build JVM Distributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: 📦 Build JVM distZip
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: distZip
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build JVM distTar
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: distTar
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
          gradle-distribution-sha-256-sum-warning: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JVM Distributions
        uses: actions/upload-artifact@v4
        with:
          name: jvm-dist
          path: build/distributions/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-jvm, build-jvm-dist]
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifact JVM
        uses: actions/download-artifact@v4
        with:
          name: jvm-package
          path: package

      - name: Download Artifact JVM Distributions
        uses: actions/download-artifact@v4
        with:
          name: jvm-dist
          path: dist

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files: |
            package/pakku.jar
            dist/*.zip
            dist/*.tar

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Xmx5g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
